# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mexico Auto &amp; Travel Insurance | Mexpro
email: customerservice@mexpro.com
description: > # this means to ignore newlines until "baseurl:"
  Online insurance quotes for taking your U.S. or Candian vehicle to Mexico.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mexpro.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

# Exclusions - Don't add these to the built site.
exclude:
  - Dockerfile
  - docker-compose.yml
